//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Demo_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUU_TRU
    {
        public string MA_CUA_HANG { get; set; }
        public string MA_MAT_HANG { get; set; }
        public Nullable<int> SO_LUONG_MAT_HANG { get; set; }
    
        public virtual CUA_HANG CUA_HANG { get; set; }
        public virtual MAT_HANG MAT_HANG { get; set; }
    }
}
